### ISSUE TITLE
Fallback mechanism automatically searching a default resource file?

### ISSUE THREAD

**Issue by shev72** [martinandert/counterpart#16]
The fallback mechanism requires the default parameter to be supplied on each call.  It would be nice if we a method could be added which would look up a default translation file if the translation did not exist. In many cases we are happy if the english translation (or another default language) is provided if the translation does not exist in the language.  it is cumbersome to have to supply the default param each time.

**Comment by shev72** [comment]
Actually I see that this may have been implemented in saknarat't fork already, , would be nice if it could be merged in to the core.

**Comment by martinandert** [comment]
You could use the (currently undocumented) `setFallbackLocale` function to use as fallback mechanism.

This is available since v0.16.5 and was introduced in [this commit](https://github.com/martinandert/counterpart/commit/38d575bae59b284fe4095c08fae09dcde9794f72).
