### ISSUE TITLE
Emit Event when translation is not found

### ISSUE THREAD

**Issue by frg** [martinandert/counterpart#21]
Is there a way to trigger an event when translation is not found? Basically when the fallback is used.

This is important because missing translations should not be silently ignored but handled appropriately for each case.

ex. Translation not found > send request to server and log an error

**Comment by martinandert** [comment]
Hi,

currently no event is emitted in this case. Your use case seems legit. Do you mind sending a pull request?

**Comment by frg** [comment]
Ill get on this later on today after work :)

**Comment by frg** [comment]
Just created a pull request. Sorry it took so long! Let me know if you need me to modify anything in the implementation @martinandert
