### ISSUE TITLE
problem with html content that contains a "%"

### ISSUE THREAD

**Issue by frg** [martinandert/counterpart#23]
Hi,
I'm getting an error when a translation contains a percentage symbol (%).

Uncaught Error: [sprintf] %</span></h3>

Any idea on how I can get around this?

Edit: I tried using the entity "&#37;" but the issue still persists

**Comment by martinandert** [comment]
Hi @frg, percentage signs need to be escaped with another percentage sign (see #2).

**Comment by frg** [comment]
Great! Thanks!. One last question, is this a sprintf quirk?

**Comment by martinandert** [comment]
Yes, it is.

**Comment by frg** [comment]
Awesome, thanks!
