### ISSUE TITLE
Pluralization Issue

### ISSUE THREAD

**Issue by janroesner** [martinandert/counterpart#24]
With:

```json
module.exports = {
  "greeting": "Hello, %(name)s!",
  "x_nights": {
    "zero": "No Night",
    "one":   "1 Night",
    "other": "%(count) Nights"
  }
}
```
executing: 

`translate('x_nights.other', {count: 3})` results in:

Uncaught Error: [sprintf] %(count) Nächte(…)

**Comment by martinandert** [comment]
Hi,

it has to be "%(count)s Nights". Notice the "s" after the ")".

**Comment by janroesner** [comment]
@martinandert: That was not obvious in the first place. Thx for your quick reaction!
