### ISSUE TITLE
Consider switching to a regularly maintained sprintf package

### ISSUE THREAD

**Issue by Temaruk** [martinandert/counterpart#25]
Thank you for your time and effort in creating this awesome package!

It occurred to me that switching to https://github.com/alexei/sprintf.js might be as simple as 2 line changes. This is the lib on which the currently used (https://github.com/maritz/node-sprintf) is based (as mentioned in its docs). 

One benefit I can see over the old one (there might be many more) is that interpolations would support computed values (functions). Would have been really useful for me. :)

**Comment by martinandert** [comment]
@Temaruk, do you mind creating a pull request? I'm currently really busy doing other things...

**Comment by Temaruk** [comment]
@martinandert I have created a PR as you requested, please check!
