### ISSUE TITLE
how to handle simple formatting like bold or italic 

### ISSUE THREAD

**Issue by timaschew** [martinandert/counterpart#29]
Would like to emphasis some parts of the translation string.
I don't see any possibility without using to `Translate` components.
Would be very nice if `Translate` supports either raw HTML or supports some basic markdown syntax like `_italic_ and __bold__` like this library here https://github.com/alexdrel/i18n-react

**Comment by martinandert** [comment]
When using react-translate-component (which itself uses counterpart), set the `unsafe` prop to `true`. See https://github.com/martinandert/react-translate-component/blob/master/spec.js for an example.

**Comment by timaschew** [comment]
thanks, that works ;)
