### ISSUE TITLE
Issue when using interpolation with numbers

### ISSUE THREAD

**Issue by maxmantz** [martinandert/counterpart#33]
I have the following setup for a table footer with pagination info:

Translations:

    app: {
      footer: 'Zeige Einträge %(start)s bis %(end)s von %(total)s'
    }

I use the component like this:

    <Translate content="app.footer"
      start={this.state.skip + 1}
      end={this.state.skip + this.state.top}
      total={this.state.total}
    />

The translation works perfectly on first load, but when I change the values for either `top` or `skip` the calculation fails, instead the numbers get concatenated like strings. See screenshot: 
![screenshot](https://cloud.githubusercontent.com/assets/6616421/14859509/b5cce018-0ca4-11e6-9f9b-e1081d1f699b.png)

Am I missing something? Is there a possibility to interpolate as a number, like `%(start)n` instead of 
`%(start)s`?

**Comment by maxmantz** [comment]
Whoops wrong repo.. will move it.

**Comment by yanndinendal** [comment]
@maxmantz :  
> Is there a possibility to interpolate as a number, like %(start)n instead of 
%(start)s?

Yes: try `'Zeige Einträge %(start)d bis %(end)d von %(total)d'`.

See: https://en.wikipedia.org/wiki/Printf_format_string#Type_field
