### ISSUE TITLE
Name of the option to select a specific pluralization

### ISSUE THREAD

**Issue by Nick-Burdo** [martinandert/counterpart#34]
Hi!
I have been using your wonderful library (by `react-translate-component`). 
When I used pluralization, I was faced with a problem. I used `notationsCount` instead of `count` as name for option to select a specific pluralization and got an error `Uncaught Invariant Violation: Interpolate expects either a format string as only child or a 'format' prop with a string value`. 
It took some time until I figured it out. 
Please emphasize in the documentation the fact that the name of the option to select a specific pluralization must be `count`.

**Comment by martinandert** [comment]
Done. Thanks!

**Comment by sondosmustafa** [comment]
Interpolate expects either a format string as only child or a `format` prop with a string value
error ? any solution !
