### ISSUE TITLE
Why is translationnotfound fired only when fallback is provided?

### ISSUE THREAD

**Issue by jiripudil** [martinandert/counterpart#43]
I was wondering, is there some special reasoning behind that decision? Even if I don't provide a fallback, I'd still like to be able to e.g. throw an error when developing or log the information to the server when on production, so that I can find out about the missing translation easily

**Comment by martinandert** [comment]
Hi @jiripudil ,

I must admit that I'm, after more than 2 years have passed, not really sure about the reasoning for this behavior. I agree that it doesn't make much sense the way it currently is and consider it a bug. It's fixed in v0.17.9. Please let me know if you notice anything odd.

Thanks!

**Comment by jiripudil** [comment]
Great, thank you for the quick response and a fix!
