### ISSUE TITLE
Passing react dom element to a placeholder

### ISSUE THREAD

**Issue by beku8** [martinandert/counterpart#45]
We are using counterpart heavily and it would be great if we can pass react dom element to a placeholder
like so 
```
// imagine the following entry
counterpart.registerTranslations('en', {
 departures: {
      available_of: '%(available)s available of total %(max)s pax'
    }
})

// and display it using
  const available = (count) => {
    return (<b>{count}</b>);
  };
 translate('departures.available_of', {available: available(departure.available), max: departure.max})
```

Is it possible to implement this, please?

**Comment by martinandert** [comment]
Hi Bilguun, I think adding direct support for React to this package is out of its scope. But react-translate-component and react-interpolate-component should help you to accomplish your use case.

**Comment by yanndinendal** [comment]
@beku8 : Hi, it should also work with [@gandi/react-translate](https://www.npmjs.com/package/@gandi/react-translate): https://github.com/Gandi/react-translate/blob/master/doc/translator.md

**Comment by yanndinendal** [comment]
@beku8 : Hi, it should also work with [@gandi/react-translate](https://www.npmjs.com/package/@gandi/react-translate), which also uses Counterpart: https://github.com/Gandi/react-translate/blob/master/doc/translator.md
