### ISSUE TITLE
Feature request: Multiple counts

### ISSUE THREAD

**Issue by pafcu** [martinandert/counterpart#47]
It would be nice to be able to specify multiple counts in case a string needs to report two or more things that may or may not be singular.

Eg.

- there is one apple and one pear
- there are %(count1)s apples and one pear
- there is one apple and %(count2)s pears
- there are %(count1)s apples and %(count2)s pears

**Comment by martinandert** [comment]
Hi @pafcu, although it'd be nice to have something like this in general, it's currently out of this library's scope.
